let def_tests_libro = Array(
    Array('libro', 'CodigoL', 1, 'cumple formato numérico', 'ADD', 'CodigoL_no_format_KO', 'El código solo debe contener números'),
    Array('libro', 'CodigoL', 2, 'cumple tamaño máximo', 'ADD', 'CodigoL_max_size_KO', 'Tamaño muy grande. Debe ser menor de 11 caracteres'),
    Array('libro', 'CodigoL', 3, 'es correcto', 'ADD', true, 'Código correcto'),
    Array('libro', 'CodigoL', 4, 'cumple formato numérico', 'EDIT', 'CodigoL_no_format_KO', 'El código solo debe contener números'),
    Array('libro', 'CodigoL', 5, 'cumple tamaño máximo', 'EDIT', 'CodigoL_max_size_KO', 'Tamaño muy grande. Debe ser menor de 11 caracteres'),
    Array('libro', 'CodigoL', 6, 'es correcto', 'EDIT', true, 'Código correcto'),
    Array('libro', 'CodigoL', 7, 'cumple formato numérico', 'SEARCH', 'CodigoL_no_format_KO', 'El código solo debe contener números'),
    Array('libro', 'CodigoL', 8, 'cumple tamaño máximo', 'SEARCH', 'CodigoL_max_size_KO', 'Tamaño muy grande. Debe ser menor de 11 caracteres'),
    Array('libro', 'CodigoL', 9, 'es correcto', 'SEARCH', true, 'Código correcto'),

    // AutoresL
    Array('libro', 'AutoresL', 10, 'cumple tamaño mínimo', 'ADD', 'AutoresL_min_size_KO', 'Tamaño muy corto. Debe tener al menos 1 carácter'),
    Array('libro', 'AutoresL', 11, 'cumple tamaño máximo', 'ADD', 'AutoresL_max_size_KO', 'Tamaño muy grande. Debe ser menor de 200 caracteres'),
    Array('libro', 'AutoresL', 12, 'cumple formato', 'ADD', 'AutoresL_no_format_KO', 'Los autores solo pueden contener letras, espacios y signos de puntuación'),
    Array('libro', 'AutoresL', 13, 'es correcto', 'ADD', true, 'Autores correctos'),
    Array('libro', 'AutoresL', 14, 'cumple tamaño mínimo', 'EDIT', 'AutoresL_min_size_KO', 'Tamaño muy corto. Debe tener al menos 1 carácter'),
    Array('libro', 'AutoresL', 15, 'cumple tamaño máximo', 'EDIT', 'AutoresL_max_size_KO', 'Tamaño muy grande. Debe ser menor de 200 caracteres'),
    Array('libro', 'AutoresL', 16, 'cumple formato', 'EDIT', 'AutoresL_no_format_KO', 'Los autores solo pueden contener letras, espacios y signos de puntuación'),
    Array('libro', 'AutoresL', 17, 'es correcto', 'EDIT', true, 'Autores correctos'),
    Array('libro', 'AutoresL', 18, 'cumple tamaño máximo', 'SEARCH', 'AutoresL_max_size_KO', 'Tamaño muy grande. Debe ser menor de 200 caracteres'),
    Array('libro', 'AutoresL', 19, 'cumple formato', 'SEARCH', 'AutoresL_no_format_KO', 'Los autores solo pueden contener letras, espacios y signos de puntuación'),
    Array('libro', 'AutoresL', 20, 'es correcto', 'SEARCH', true, 'Autores correctos'),

    // TituloL
    Array('libro', 'TituloL', 21, 'cumple tamaño mínimo', 'ADD', 'TituloL_min_size_KO', 'Tamaño muy corto. Debe tener al menos 1 carácter'),
    Array('libro', 'TituloL', 22, 'cumple tamaño máximo', 'ADD', 'TituloL_max_size_KO', 'Tamaño muy grande. Debe ser menor de 100 caracteres'),
    Array('libro', 'TituloL', 23, 'cumple formato', 'ADD', 'TituloL_no_format_KO', 'El título solo puede contener letras, números, espacios y signos de puntuación'),
    Array('libro', 'TituloL', 24, 'es correcto', 'ADD', true, 'Título correcto'),
    Array('libro', 'TituloL', 25, 'cumple tamaño mínimo', 'EDIT', 'TituloL_min_size_KO', 'Tamaño muy corto. Debe tener al menos 1 carácter'),
    Array('libro', 'TituloL', 26, 'cumple tamaño máximo', 'EDIT', 'TituloL_max_size_KO', 'Tamaño muy grande. Debe ser menor de 100 caracteres'),
    Array('libro', 'TituloL', 27, 'cumple formato', 'EDIT', 'TituloL_no_format_KO', 'El título solo puede contener letras, números, espacios y signos de puntuación'),
    Array('libro', 'TituloL', 28, 'es correcto', 'EDIT', true, 'Título correcto'),
    Array('libro', 'TituloL', 29, 'cumple tamaño máximo', 'SEARCH', 'TituloL_max_size_KO', 'Tamaño muy grande. Debe ser menor de 100 caracteres'),
    Array('libro', 'TituloL', 30, 'cumple formato', 'SEARCH', 'TituloL_no_format_KO', 'El título solo puede contener letras, números, espacios y signos de puntuación'),
    Array('libro', 'TituloL', 31, 'es correcto', 'SEARCH', true, 'Título correcto'),

    // ISBN
    Array('libro', 'ISBN', 32, 'cumple tamaño mínimo', 'ADD', 'ISBN_min_size_KO', 'Tamaño muy corto. Debe tener al menos 13 caracteres'),
    Array('libro', 'ISBN', 33, 'cumple tamaño máximo', 'ADD', 'ISBN_max_size_KO', 'Tamaño muy grande. Debe ser menor de 13 caracteres'),
    Array('libro', 'ISBN', 34, 'cumple formato', 'ADD', 'ISBN_no_format_KO', 'El ISBN solo puede contener números y X'),
    Array('libro', 'ISBN', 35, 'es correcto', 'ADD', true, 'ISBN correcto'),
    Array('libro', 'ISBN', 36, 'cumple tamaño mínimo', 'EDIT', 'ISBN_min_size_KO', 'Tamaño muy corto. Debe tener al menos 13 caracteres'),
    Array('libro', 'ISBN', 37, 'cumple tamaño máximo', 'EDIT', 'ISBN_max_size_KO', 'Tamaño muy grande. Debe ser menor de 13 caracteres'),
    Array('libro', 'ISBN', 38, 'cumple formato', 'EDIT', 'ISBN_no_format_KO', 'El ISBN solo puede contener números y X'),
    Array('libro', 'ISBN', 39, 'es correcto', 'EDIT', true, 'ISBN correcto'),
    Array('libro', 'ISBN', 40, 'cumple tamaño máximo', 'SEARCH', 'ISBN_max_size_KO', 'Tamaño muy grande. Debe ser menor de 13 caracteres'),
    Array('libro', 'ISBN', 41, 'cumple formato', 'SEARCH', 'ISBN_no_format_KO', 'El ISBN solo puede contener números y X '),
    Array('libro', 'ISBN', 42, 'es correcto', 'SEARCH', true, 'ISBN correcto'),

    // PagIniL
    Array('libro', 'PagIniL', 43, 'cumple tamaño mínimo', 'ADD', 'PagIniL_min_size_KO', 'Tamaño muy corto. Debe tener al menos 1 carácter'),
    Array('libro', 'PagIniL', 44, 'cumple tamaño máximo', 'ADD', 'PagIniL_max_size_KO', 'Tamaño muy grande. Debe ser menor de 4 caracteres'),
    Array('libro', 'PagIniL', 45, 'cumple formato', 'ADD', 'PagIniL_no_digit_KO', 'La página inicial debe ser un número'),
    Array('libro', 'PagIniL', 46, 'es correcto', 'ADD', true, 'Página inicial correcta'),
    Array('libro', 'PagIniL', 47, 'cumple tamaño mínimo', 'EDIT', 'PagIniL_min_size_KO', 'Tamaño muy corto. Debe tener al menos 1 carácter'),
    Array('libro', 'PagIniL', 48, 'cumple tamaño máximo', 'EDIT', 'PagIniL_max_size_KO', 'Tamaño muy grande. Debe ser menor de 4 caracteres'),
    Array('libro', 'PagIniL', 49, 'cumple formato', 'EDIT', 'PagIniL_no_digit_KO', 'La página inicial debe ser un número'),
    Array('libro', 'PagIniL', 50, 'es correcto', 'EDIT', true, 'Página inicial correcta'),
    Array('libro', 'PagIniL', 51, 'cumple tamaño máximo', 'SEARCH', 'PagIniL_max_size_KO', 'Tamaño muy grande. Debe ser menor de 4 caracteres'),
    Array('libro', 'PagIniL', 52, 'cumple formato', 'SEARCH', 'PagIniL_no_digit_KO', 'La página inicial debe ser un número'),
    Array('libro', 'PagIniL', 53, 'es correcto', 'SEARCH', true, 'Página inicial correcta'),

    // PagFinL
    Array('libro', 'PagFinL', 54, 'cumple tamaño mínimo', 'ADD', 'PagFinL_min_size_KO', 'Tamaño muy corto. Debe tener al menos 1 carácter'),
    Array('libro', 'PagFinL', 55, 'cumple tamaño máximo', 'ADD', 'PagFinL_max_size_KO', 'Tamaño muy grande. Debe ser menor de 4 caracteres'),
    Array('libro', 'PagFinL', 56, 'cumple formato', 'ADD', 'PagFinL_no_digit_KO', 'La página final debe ser un número'),
    Array('libro', 'PagFinL', 57, 'es correcto', 'ADD', true, 'Página final correcta'),
    Array('libro', 'PagFinL', 58, 'cumple tamaño mínimo', 'EDIT', 'PagFinL_min_size_KO', 'Tamaño muy corto. Debe tener al menos 1 carácter'),
    Array('libro', 'PagFinL', 59, 'cumple tamaño máximo', 'EDIT', 'PagFinL_max_size_KO', 'Tamaño muy grande. Debe ser menor de 4 caracteres'),
    Array('libro', 'PagFinL', 60, 'cumple formato', 'EDIT', 'PagFinL_no_digit_KO', 'La página final debe ser un número'),
    Array('libro', 'PagFinL', 61, 'es correcto', 'EDIT', true, 'Página final correcta'),
    Array('libro', 'PagFinL', 62, 'cumple tamaño máximo', 'SEARCH', 'PagFinL_max_size_KO', 'Tamaño muy grande. Debe ser menor de 4 caracteres'),
    Array('libro', 'PagFinL', 63, 'cumple formato', 'SEARCH', 'PagFinL_no_digit_KO', 'La página final debe ser un número'),
    Array('libro', 'PagFinL', 64, 'es correcto', 'SEARCH', true, 'Página final correcta'),

    // VolumenL
    Array('libro', 'VolumenL', 65, 'cumple tamaño mínimo', 'ADD', 'VolumenL_min_size_KO', 'Tamaño muy corto. Debe tener al menos 1 carácter'),
    Array('libro', 'VolumenL', 66, 'cumple tamaño máximo', 'ADD', 'VolumenL_max_size_KO', 'Tamaño muy grande. Debe ser menor de 4 caracteres'),
    Array('libro', 'VolumenL', 67, 'cumple formato', 'ADD', 'VolumenL_format_KO', 'El volumen debe ser un número'),
    Array('libro', 'VolumenL', 68, 'es correcto', 'ADD', true, 'Volumen correcto'),
    Array('libro', 'VolumenL', 69, 'cumple tamaño mínimo', 'EDIT', 'VolumenL_min_size_KO', 'Tamaño muy corto. Debe tener al menos 1 carácter'),
    Array('libro', 'VolumenL', 70, 'cumple tamaño máximo', 'EDIT', 'VolumenL_max_size_KO', 'Tamaño muy grande. Debe ser menor de 4 caracteres'),
    Array('libro', 'VolumenL', 71, 'cumple formato', 'EDIT', 'VolumenL_format_KO', 'El volumen debe ser un número'),
    Array('libro', 'VolumenL', 72, 'es correcto', 'EDIT', true, 'Volumen correcto'),
    Array('libro', 'VolumenL', 73, 'cumple tamaño máximo', 'SEARCH', 'VolumenL_max_size_KO', 'Tamaño muy grande. Debe ser menor de 4 caracteres'),
    Array('libro', 'VolumenL', 74, 'cumple formato', 'SEARCH', 'VolumenL_format_KO', 'El volumen debe ser un número'),
    Array('libro', 'VolumenL', 75, 'es correcto', 'SEARCH', true, 'Volumen correcto'),

    // EditorialL
    Array('libro', 'EditorialL', 76, 'cumple tamaño mínimo', 'ADD', 'EditorialL_min_size_KO', 'Tamaño muy corto. Debe tener al menos 1 carácter'),
    Array('libro', 'EditorialL', 77, 'cumple tamaño máximo', 'ADD', 'EditorialL_max_size_KO', 'Tamaño muy grande. Debe ser menor de 100 caracteres'),
    Array('libro', 'EditorialL', 78, 'cumple formato', 'ADD', 'EditorialL_no_format_KO', 'La editorial solo puede contener letras, números, espacios y signos de puntuación'),
    Array('libro', 'EditorialL', 79, 'es correcto', 'ADD', true, 'Editorial correcta'),
    Array('libro', 'EditorialL', 80, 'cumple tamaño mínimo', 'EDIT', 'EditorialL_min_size_KO', 'Tamaño muy corto. Debe tener al menos 1 carácter'),
    Array('libro', 'EditorialL', 81, 'cumple tamaño máximo', 'EDIT', 'EditorialL_max_size_KO', 'Tamaño muy grande. Debe ser menor de 100 caracteres'),
    Array('libro', 'EditorialL', 82, 'cumple formato', 'EDIT', 'EditorialL_no_format_KO', 'La editorial solo puede contener letras, números, espacios y signos de puntuación'),
    Array('libro', 'EditorialL', 83, 'es correcto', 'EDIT', true, 'Editorial correcta'),
    Array('libro', 'EditorialL', 84, 'cumple tamaño máximo', 'SEARCH', 'EditorialL_max_size_KO', 'Tamaño muy grande. Debe ser menor de 100 caracteres'),
    Array('libro', 'EditorialL', 85, 'cumple formato', 'SEARCH', 'EditorialL_no_format_KO', 'La editorial solo puede contener letras, números, espacios y signos de puntuación'),
    Array('libro', 'EditorialL', 86, 'es correcto', 'SEARCH', true, 'Editorial correcta'),

    // FechaPublicacionL
    Array('libro', 'FechaPublicacionL', 87, 'cumple formato fecha', 'ADD', 'FechaPublicacionL_format_KO', 'La fecha debe tener formato dd/mm/aaaa'),
    Array('libro', 'FechaPublicacionL', 88, 'es fecha válida', 'ADD', 'FechaPublicacionL_no_date_KO', 'La fecha debe ser una fecha válida'),
    Array('libro', 'FechaPublicacionL', 89, 'es correcto', 'ADD', true, 'Fecha de publicación correcta'),
    Array('libro', 'FechaPublicacionL', 90, 'cumple formato fecha', 'EDIT', 'FechaPublicacionL_format_KO', 'La fecha debe tener formato dd/mm/aaaa'),
    Array('libro', 'FechaPublicacionL', 91, 'es fecha válida', 'EDIT', 'FechaPublicacionL_no_date_KO', 'La fecha debe ser una fecha válida'),
    Array('libro', 'FechaPublicacionL', 92, 'es correcto', 'EDIT', true, 'Fecha de publicación correcta'),
    Array('libro', 'FechaPublicacionL', 93, 'cumple formato fecha', 'SEARCH', 'FechaPublicacionL_format_KO', 'La fecha debe tener formato dd/mm/aaaa'),
    Array('libro', 'FechaPublicacionL', 94, 'es fecha válida', 'SEARCH', 'FechaPublicacionL_no_date_KO', 'La fecha debe ser una fecha válida'),
    Array('libro', 'FechaPublicacionL', 95, 'es correcto', 'SEARCH', true, 'Fecha de publicación correcta'),

    // EditorL
    Array('libro', 'EditorL', 96, 'cumple tamaño mínimo', 'ADD', 'EditorL_min_size_KO', 'Tamaño muy corto. Debe tener al menos 1 carácter'),
    Array('libro', 'EditorL', 97, 'cumple tamaño máximo', 'ADD', 'EditorL_max_size_KO', 'Tamaño muy grande. Debe ser menor de 100 caracteres'),
    Array('libro', 'EditorL', 98, 'cumple formato', 'ADD', 'EditorL_no_format_KO', 'El editor solo puede contener letras, espacios y signos de puntuación'),
    Array('libro', 'EditorL', 99, 'es correcto', 'ADD', true, 'Editor correcto'),
    Array('libro', 'EditorL', 100, 'cumple tamaño mínimo', 'EDIT', 'EditorL_min_size_KO', 'Tamaño muy corto. Debe tener al menos 1 carácter'),
    Array('libro', 'EditorL', 101, 'cumple tamaño máximo', 'EDIT', 'EditorL_max_size_KO', 'Tamaño muy grande. Debe ser menor de 100 caracteres'),
    Array('libro', 'EditorL', 102, 'cumple formato', 'EDIT', 'EditorL_no_format_KO', 'El editor solo puede contener letras, espacios y signos de puntuación'),
    Array('libro', 'EditorL', 103, 'es correcto', 'EDIT', true, 'Editor correcto'),
    Array('libro', 'EditorL', 104, 'cumple tamaño máximo', 'SEARCH', 'EditorL_max_size_KO', 'Tamaño muy grande. Debe ser menor de 100 caracteres'),
    Array('libro', 'EditorL', 105, 'cumple formato', 'SEARCH', 'EditorL_no_format_KO', 'El editor solo puede contener letras, espacios y signos de puntuación'),
    Array('libro', 'EditorL', 106, 'es correcto', 'SEARCH', true, 'Editor correcto'),

    // PaisEdicionL
    Array('libro', 'PaisEdicionL', 107, 'cumple tamaño mínimo', 'ADD', 'PaisEdicionL_min_size_KO', 'Tamaño muy corto. Debe tener al menos 1 carácter'),
    Array('libro', 'PaisEdicionL', 108, 'cumple tamaño máximo', 'ADD', 'PaisEdicionL_max_size_KO', 'Tamaño muy grande. Debe ser menor de 20 caracteres'),
    Array('libro', 'PaisEdicionL', 109, 'cumple formato', 'ADD', 'PaisEdicionL_no_format_KO', 'El país solo puede contener letras'),
    Array('libro', 'PaisEdicionL', 110, 'es correcto', 'ADD', true, 'País de edición correcto'),
    Array('libro', 'PaisEdicionL', 111, 'cumple tamaño mínimo', 'EDIT', 'PaisEdicionL_min_size_KO', 'Tamaño muy corto. Debe tener al menos 1 carácter'),
    Array('libro', 'PaisEdicionL', 112, 'cumple tamaño máximo', 'EDIT', 'PaisEdicionL_max_size_KO', 'Tamaño muy grande. Debe ser menor de 20 caracteres'),
    Array('libro', 'PaisEdicionL', 113, 'cumple formato', 'EDIT', 'PaisEdicionL_no_format_KO', 'El país solo puede contener letras'),
    Array('libro', 'PaisEdicionL', 114, 'es correcto', 'EDIT', true, 'País de edición correcto'),
    Array('libro', 'PaisEdicionL', 115, 'cumple tamaño máximo', 'SEARCH', 'PaisEdicionL_max_size_KO', 'Tamaño muy grande. Debe ser menor de 20 caracteres'),
    Array('libro', 'PaisEdicionL', 116, 'cumple formato', 'SEARCH', 'PaisEdicionL_no_format_KO', 'El país solo puede contener letras'),
    Array('libro', 'PaisEdicionL', 117, 'es correcto', 'SEARCH', true, 'País de edición correcto'),

    // nuevo_archivopdfL
    Array('libro', 'nuevo_archivopdfL', 118, 'cumple tamaño máximo fichero', 'ADD', 'archivopdfL_max_size_file_KO', 'El tamaño del fichero debe ser menor de 2MB'),
    Array('libro', 'nuevo_archivopdfL', 119, 'cumple tipo fichero', 'ADD', 'archivopdfL_type_file_KO', 'El fichero debe ser PDF'),
    Array('libro', 'nuevo_archivopdfL', 120, 'cumple formato nombre', 'ADD', 'archivopdfL_format_name_file_KO', 'El nombre del fichero solo puede contener letras y punto'),
    Array('libro', 'nuevo_archivopdfL', 121, 'cumple tamaño mínimo nombre', 'ADD', 'archivopdfL_min_size_name_KO', 'El nombre debe tener al menos 11 caracteres'),
    Array('libro', 'nuevo_archivopdfL', 122, 'cumple tamaño máximo nombre', 'ADD', 'archivopdfL_max_size_name_KO', 'El nombre debe tener menos de 104 caracteres'),
    Array('libro', 'nuevo_archivopdfL', 123, 'es correcto', 'ADD', true, 'Archivo PDF correcto'),
    Array('libro', 'nuevo_archivopdfL', 124, 'cumple tamaño máximo fichero', 'EDIT', 'archivopdfL_max_size_file_KO', 'El tamaño del fichero debe ser menor de 2MB'),
    Array('libro', 'nuevo_archivopdfL', 125, 'cumple tipo fichero', 'EDIT', 'archivopdfL_type_file_KO', 'El fichero debe ser PDF'),
    Array('libro', 'nuevo_archivopdfL', 126, 'cumple formato nombre', 'EDIT', 'archivopdfL_format_name_file_KO', 'El nombre del fichero solo puede contener letras y punto'),
    Array('libro', 'nuevo_archivopdfL', 127, 'cumple tamaño mínimo nombre', 'EDIT', 'archivopdfL_min_size_name_KO', 'El nombre debe tener al menos 11 caracteres'),
    Array('libro', 'nuevo_archivopdfL', 128, 'cumple tamaño máximo nombre', 'EDIT', 'archivopdfL_max_size_name_KO', 'El nombre debe tener menos de 104 caracteres'),
    Array('libro', 'nuevo_archivopdfL', 129, 'es correcto', 'EDIT', true, 'Archivo PDF correcto')
);

let pruebas_libro = Array(

    //CodigoL
    Array('libro', 'CodigoL', 1, 1, 'ADD', 'abc123', 'CodigoL_no_format_KO'),
    Array('libro', 'CodigoL', 1, 2, 'ADD', '123', true),
    Array('libro', 'CodigoL', 2, 3, 'ADD', '12345678901234', 'CodigoL_max_size_KO'),
    Array('libro', 'CodigoL', 2, 4, 'ADD', '12345', true),
    Array('libro', 'CodigoL', 3, 5, 'ADD', '12345', true),
    Array('libro', 'CodigoL', 4, 6, 'EDIT', 'abc123', 'CodigoL_no_format_KO'),
    Array('libro', 'CodigoL', 4, 7, 'EDIT', '123', true),
    Array('libro', 'CodigoL', 5, 8, 'EDIT', '12345678901234', 'CodigoL_max_size_KO'),
    Array('libro', 'CodigoL', 5, 9, 'EDIT', '12345', true),
    Array('libro', 'CodigoL', 6, 10, 'EDIT', '12345', true),
    Array('libro', 'CodigoL', 7, 11, 'SEARCH', 'abc123', 'CodigoL_no_format_KO'),
    Array('libro', 'CodigoL', 7, 12, 'SEARCH', '123', true),
    Array('libro', 'CodigoL', 8, 13, 'SEARCH', '12345678901234', 'CodigoL_max_size_KO'),
    Array('libro', 'CodigoL', 8, 14, 'SEARCH', '12345', true),
    Array('libro', 'CodigoL', 9, 15, 'SEARCH', '12345', true),
    
    // AutoresL
    Array('libro', 'AutoresL', 10, 16, 'ADD', '', 'AutoresL_min_size_KO'),
    Array('libro', 'AutoresL', 10, 17, 'ADD', 'Juan Pérez', true),
    Array('libro', 'AutoresL', 11, 18, 'ADD', 'a'.repeat(201), 'AutoresL_max_size_KO'),
    Array('libro', 'AutoresL', 11, 19, 'ADD', 'Juan Pérez, María García', true),
    Array('libro', 'AutoresL', 12, 20, 'ADD', 'Juan123', 'AutoresL_no_format_KO'),
    Array('libro', 'AutoresL', 12, 21, 'ADD', 'Juan Pérez, María García', true),
    Array('libro', 'AutoresL', 13, 22, 'ADD', 'Juan Pérez, María García', true),
    Array('libro', 'AutoresL', 14, 23, 'EDIT', '', 'AutoresL_min_size_KO'),
    Array('libro', 'AutoresL', 14, 24, 'EDIT', 'Juan Pérez', true),
    Array('libro', 'AutoresL', 15, 25, 'EDIT', 'a'.repeat(201), 'AutoresL_max_size_KO'),
    Array('libro', 'AutoresL', 15, 26, 'EDIT', 'Juan Pérez, María García', true),
    Array('libro', 'AutoresL', 16, 27, 'EDIT', 'Juan123', 'AutoresL_no_format_KO'),
    Array('libro', 'AutoresL', 16, 28, 'EDIT', 'Juan Pérez, María García', true),
    Array('libro', 'AutoresL', 17, 29, 'EDIT', 'Juan Pérez, María García', true),
    Array('libro', 'AutoresL', 18, 30, 'SEARCH', 'a'.repeat(201), 'AutoresL_max_size_KO'),
    Array('libro', 'AutoresL', 18, 31, 'SEARCH', 'Juan Pérez, María García', true),
    Array('libro', 'AutoresL', 19, 32, 'SEARCH', 'Juan123', 'AutoresL_no_format_KO'),
    Array('libro', 'AutoresL', 19, 33, 'SEARCH', 'Juan Pérez, María García', true),
    Array('libro', 'AutoresL', 20, 34, 'SEARCH', 'Juan Pérez, María García', true),

    // TituloL
    Array('libro', 'TituloL', 21, 35, 'ADD', '', 'TituloL_min_size_KO'),
    Array('libro', 'TituloL', 21, 36, 'ADD', 'El Quijote', true),
    Array('libro', 'TituloL', 22, 37, 'ADD', 'a'.repeat(101), 'TituloL_max_size_KO'),
    Array('libro', 'TituloL', 22, 38, 'ADD', 'Don Quijote de la Mancha', true),
    Array('libro', 'TituloL', 23, 39, 'ADD', 'El Quijote @', 'TituloL_no_format_KO'),
    Array('libro', 'TituloL', 23, 40, 'ADD', 'Don Quijote de la Mancha 2', true),
    Array('libro', 'TituloL', 24, 41, 'ADD', 'Don Quijote de la Mancha', true),
    Array('libro', 'TituloL', 25, 42, 'EDIT', '', 'TituloL_min_size_KO'),
    Array('libro', 'TituloL', 25, 43, 'EDIT', 'El Quijote', true),
    Array('libro', 'TituloL', 26, 44, 'EDIT', 'a'.repeat(101), 'TituloL_max_size_KO'),
    Array('libro', 'TituloL', 26, 45, 'EDIT', 'Don Quijote de la Mancha', true),
    Array('libro', 'TituloL', 27, 46, 'EDIT', 'El Quijote @', 'TituloL_no_format_KO'),
    Array('libro', 'TituloL', 27, 47, 'EDIT', 'Don Quijote de la Mancha 2', true),
    Array('libro', 'TituloL', 28, 48, 'EDIT', 'Don Quijote de la Mancha', true),
    Array('libro', 'TituloL', 29, 49, 'SEARCH', 'a'.repeat(101), 'TituloL_max_size_KO'),
    Array('libro', 'TituloL', 29, 50, 'SEARCH', 'Don Quijote de la Mancha', true),
    Array('libro', 'TituloL', 30, 51, 'SEARCH', 'El Quijote @', 'TituloL_no_format_KO'),
    Array('libro', 'TituloL', 30, 52, 'SEARCH', 'Don Quijote de la Mancha 2', true),
    Array('libro', 'TituloL', 31, 53, 'SEARCH', 'Don Quijote de la Mancha', true),

    // ISBN
    Array('libro', 'ISBN', 32, 54, 'ADD', '123456789', 'ISBN_min_size_KO'),
    Array('libro', 'ISBN', 32, 55, 'ADD', '1111111111111', true),
    Array('libro', 'ISBN', 33, 56, 'ADD', '12345678901234', 'ISBN_max_size_KO'),
    Array('libro', 'ISBN', 33, 57, 'ADD', '1111111111111', true),
    Array('libro', 'ISBN', 34, 58, 'ADD', '978@012345611', 'ISBN_no_format_KO'),
    Array('libro', 'ISBN', 34, 59, 'ADD', '1111111111111', true),
    Array('libro', 'ISBN', 35, 60, 'ADD', '1111111111111', true),
    Array('libro', 'ISBN', 36, 61, 'EDIT', '123456789', 'ISBN_min_size_KO'),
    Array('libro', 'ISBN', 36, 62, 'EDIT', '1111111111111', true),
    Array('libro', 'ISBN', 37, 63, 'EDIT', '12345678901234', 'ISBN_max_size_KO'),
    Array('libro', 'ISBN', 37, 64, 'EDIT', '1111111111111', true),
    Array('libro', 'ISBN', 38, 65, 'EDIT', '978@01-256111', 'ISBN_no_format_KO'),
    Array('libro', 'ISBN', 38, 66, 'EDIT', '1111111111111', true),
    Array('libro', 'ISBN', 39, 67, 'EDIT', '1111111111111', true),
    Array('libro', 'ISBN', 40, 68, 'SEARCH', '12345678901234', 'ISBN_max_size_KO'),
    Array('libro', 'ISBN', 40, 69, 'SEARCH', '1111111111111', true),
    Array('libro', 'ISBN', 41, 70, 'SEARCH', '978@012345611', 'ISBN_no_format_KO'),
    Array('libro', 'ISBN', 41, 71, 'SEARCH', '1111111111111', true),
    Array('libro', 'ISBN', 42, 72, 'SEARCH', '1111111111111', true),

    // PagIniL
    Array('libro', 'PagIniL', 43, 73, 'ADD', '', 'PagIniL_min_size_KO'),
    Array('libro', 'PagIniL', 43, 74, 'ADD', '1', true),
    Array('libro', 'PagIniL', 44, 75, 'ADD', '12345', 'PagIniL_max_size_KO'),
    Array('libro', 'PagIniL', 44, 76, 'ADD', '123', true),
    Array('libro', 'PagIniL', 45, 77, 'ADD', 'abc', 'PagIniL_no_digit_KO'),
    Array('libro', 'PagIniL', 45, 78, 'ADD', '42', true),
    Array('libro', 'PagIniL', 46, 79, 'ADD', '42', true),
    Array('libro', 'PagIniL', 47, 80, 'EDIT', '', 'PagIniL_min_size_KO'),
    Array('libro', 'PagIniL', 47, 81, 'EDIT', '1', true),
    Array('libro', 'PagIniL', 48, 82, 'EDIT', '12345', 'PagIniL_max_size_KO'),
    Array('libro', 'PagIniL', 48, 83, 'EDIT', '123', true),
    Array('libro', 'PagIniL', 49, 84, 'EDIT', 'abc', 'PagIniL_no_digit_KO'),
    Array('libro', 'PagIniL', 49, 85, 'EDIT', '42', true),
    Array('libro', 'PagIniL', 50, 86, 'EDIT', '42', true),
    Array('libro', 'PagIniL', 51, 87, 'SEARCH', '12345', 'PagIniL_max_size_KO'),
    Array('libro', 'PagIniL', 51, 88, 'SEARCH', '123', true),
    Array('libro', 'PagIniL', 52, 89, 'SEARCH', 'abc', 'PagIniL_no_digit_KO'),
    Array('libro', 'PagIniL', 52, 90, 'SEARCH', '42', true),
    Array('libro', 'PagIniL', 53, 91, 'SEARCH', '42', true),

    // PagFinL
    Array('libro', 'PagFinL', 54, 92, 'ADD', '', 'PagFinL_min_size_KO'),
    Array('libro', 'PagFinL', 54, 93, 'ADD', '100', true),
    Array('libro', 'PagFinL', 55, 94, 'ADD', '12345', 'PagFinL_max_size_KO'),
    Array('libro', 'PagFinL', 55, 95, 'ADD', '999', true),
    Array('libro', 'PagFinL', 56, 96, 'ADD', 'abc', 'PagFinL_no_digit_KO'),
    Array('libro', 'PagFinL', 56, 97, 'ADD', '200', true),
    Array('libro', 'PagFinL', 57, 98, 'ADD', '200', true),
    Array('libro', 'PagFinL', 58, 99, 'EDIT', '', 'PagFinL_min_size_KO'),
    Array('libro', 'PagFinL', 58, 100, 'EDIT', '100', true),
    Array('libro', 'PagFinL', 59, 101, 'EDIT', '12345', 'PagFinL_max_size_KO'),
    Array('libro', 'PagFinL', 59, 102, 'EDIT', '999', true),
    Array('libro', 'PagFinL', 60, 103, 'EDIT', 'abc', 'PagFinL_no_digit_KO'),
    Array('libro', 'PagFinL', 60, 104, 'EDIT', '200', true),
    Array('libro', 'PagFinL', 61, 105, 'EDIT', '200', true),
    Array('libro', 'PagFinL', 62, 106, 'SEARCH', '12345', 'PagFinL_max_size_KO'),
    Array('libro', 'PagFinL', 62, 107, 'SEARCH', '999', true),
    Array('libro', 'PagFinL', 63, 108, 'SEARCH', 'abc', 'PagFinL_no_digit_KO'),
    Array('libro', 'PagFinL', 63, 109, 'SEARCH', '200', true),
    Array('libro', 'PagFinL', 64, 110, 'SEARCH', '200', true),

    // VolumenL
    Array('libro', 'VolumenL', 65, 111, 'ADD', '', 'VolumenL_min_size_KO'),
    Array('libro', 'VolumenL', 65, 112, 'ADD', '1', true),
    Array('libro', 'VolumenL', 66, 113, 'ADD', '12345', 'VolumenL_max_size_KO'),
    Array('libro', 'VolumenL', 66, 114, 'ADD', '42', true),
    Array('libro', 'VolumenL', 67, 115, 'ADD', 'abc', 'VolumenL_format_KO'),
    Array('libro', 'VolumenL', 67, 116, 'ADD', '7', true),
    Array('libro', 'VolumenL', 68, 117, 'ADD', '7', true),
    Array('libro', 'VolumenL', 69, 118, 'EDIT', '', 'VolumenL_min_size_KO'),
    Array('libro', 'VolumenL', 69, 119, 'EDIT', '1', true),
    Array('libro', 'VolumenL', 70, 120, 'EDIT', '12345', 'VolumenL_max_size_KO'),
    Array('libro', 'VolumenL', 70, 121, 'EDIT', '42', true),
    Array('libro', 'VolumenL', 71, 122, 'EDIT', 'abc', 'VolumenL_format_KO'),
    Array('libro', 'VolumenL', 71, 123, 'EDIT', '7', true),
    Array('libro', 'VolumenL', 72, 124, 'EDIT', '7', true),
    Array('libro', 'VolumenL', 73, 125, 'SEARCH', '12345', 'VolumenL_max_size_KO'),
    Array('libro', 'VolumenL', 73, 126, 'SEARCH', '42', true),
    Array('libro', 'VolumenL', 74, 127, 'SEARCH', 'abc', 'VolumenL_format_KO'),
    Array('libro', 'VolumenL', 74, 128, 'SEARCH', '7', true),
    Array('libro', 'VolumenL', 75, 129, 'SEARCH', '7', true),

    // EditorialL
    Array('libro', 'EditorialL', 76, 130, 'ADD', '', 'EditorialL_min_size_KO'),
    Array('libro', 'EditorialL', 76, 131, 'ADD', 'Planeta', true),
    Array('libro', 'EditorialL', 77, 132, 'ADD', 'a'.repeat(101), 'EditorialL_max_size_KO'),
    Array('libro', 'EditorialL', 77, 133, 'ADD', 'Editorial Planeta', true),
    Array('libro', 'EditorialL', 78, 134, 'ADD', 'Editorial@123', 'EditorialL_no_format_KO'),
    Array('libro', 'EditorialL', 78, 135, 'ADD', 'Editorial Planeta S.A.', true),
    Array('libro', 'EditorialL', 79, 136, 'ADD', 'Editorial Planeta S.A.', true),
    Array('libro', 'EditorialL', 80, 137, 'EDIT', '', 'EditorialL_min_size_KO'),
    Array('libro', 'EditorialL', 80, 138, 'EDIT', 'Planeta', true),
    Array('libro', 'EditorialL', 81, 139, 'EDIT', 'a'.repeat(101), 'EditorialL_max_size_KO'),
    Array('libro', 'EditorialL', 81, 140, 'EDIT', 'Editorial Planeta', true),
    Array('libro', 'EditorialL', 82, 141, 'EDIT', 'Editorial@123', 'EditorialL_no_format_KO'),
    Array('libro', 'EditorialL', 82, 142, 'EDIT', 'Editorial Planeta S.A.', true),
    Array('libro', 'EditorialL', 83, 143, 'EDIT', 'Editorial Planeta S.A.', true),
    Array('libro', 'EditorialL', 84, 144, 'SEARCH', 'a'.repeat(101), 'EditorialL_max_size_KO'),
    Array('libro', 'EditorialL', 84, 145, 'SEARCH', 'Editorial Planeta', true),
    Array('libro', 'EditorialL', 85, 146, 'SEARCH', 'Editorial@123', 'EditorialL_no_format_KO'),
    Array('libro', 'EditorialL', 85, 147, 'SEARCH', 'Editorial Planeta S.A.', true),
    Array('libro', 'EditorialL', 86, 148, 'SEARCH', 'Editorial Planeta S.A.', true),

    // FechaPublicacionL
    Array('libro', 'FechaPublicacionL', 87, 149, 'ADD', '01/01/2023', 'FechaPublicacionL_format_KO'),
    Array('libro', 'FechaPublicacionL', 87, 150, 'ADD', '2023-01-01', true),
    Array('libro', 'FechaPublicacionL', 88, 151, 'ADD', '2023-13-32', 'FechaPublicacionL_no_date_KO'),
    Array('libro', 'FechaPublicacionL', 88, 152, 'ADD', '2023-06-15', true),
    Array('libro', 'FechaPublicacionL', 89, 153, 'ADD', '2023-06-21', true),
    Array('libro', 'FechaPublicacionL', 90, 154, 'EDIT', '01/01/2023', 'FechaPublicacionL_format_KO'),
    Array('libro', 'FechaPublicacionL', 90, 155, 'EDIT', '2023-01-01', true),
    Array('libro', 'FechaPublicacionL', 91, 156, 'EDIT', '2023-13-32', 'FechaPublicacionL_no_date_KO'),
    Array('libro', 'FechaPublicacionL', 91, 157, 'EDIT', '2023-06-15', true),
    Array('libro', 'FechaPublicacionL', 92, 158, 'EDIT', '2023-06-15', true),
    Array('libro', 'FechaPublicacionL', 93, 159, 'SEARCH', '01/01/2023', 'FechaPublicacionL_format_KO'),
    Array('libro', 'FechaPublicacionL', 93, 160, 'SEARCH', '2023-01-01', true),
    Array('libro', 'FechaPublicacionL', 94, 161, 'SEARCH', '2023-13-32', 'FechaPublicacionL_no_date_KO'),
    Array('libro', 'FechaPublicacionL', 94, 162, 'SEARCH', '2023-06-23', true),
    Array('libro', 'FechaPublicacionL', 95, 163, 'SEARCH', '2023-06-15', true),

    // EditorL
    Array('libro', 'EditorL', 96, 164, 'ADD', '', 'EditorL_min_size_KO'),
    Array('libro', 'EditorL', 96, 165, 'ADD', 'Juan Pérez', true),
    Array('libro', 'EditorL', 97, 166, 'ADD', 'a'.repeat(101), 'EditorL_max_size_KO'),
    Array('libro', 'EditorL', 97, 167, 'ADD', 'María García', true),
    Array('libro', 'EditorL', 98, 168, 'ADD', 'Editor@123', 'EditorL_no_format_KO'),
    Array('libro', 'EditorL', 98, 169, 'ADD', 'José Martínez', true),
    Array('libro', 'EditorL', 99, 170, 'ADD', 'José Martínez', true),
    Array('libro', 'EditorL', 100, 171, 'EDIT', '', 'EditorL_min_size_KO'),
    Array('libro', 'EditorL', 100, 172, 'EDIT', 'Juan Pérez', true),
    Array('libro', 'EditorL', 101, 173, 'EDIT', 'a'.repeat(101), 'EditorL_max_size_KO'),
    Array('libro', 'EditorL', 101, 174, 'EDIT', 'María García', true),
    Array('libro', 'EditorL', 102, 175, 'EDIT', 'Editor@123', 'EditorL_no_format_KO'),
    Array('libro', 'EditorL', 102, 176, 'EDIT', 'José Martínez', true),
    Array('libro', 'EditorL', 103, 177, 'EDIT', 'José Martínez', true),
    Array('libro', 'EditorL', 104, 178, 'SEARCH', 'a'.repeat(101), 'EditorL_max_size_KO'),
    Array('libro', 'EditorL', 104, 179, 'SEARCH', 'María García', true),
    Array('libro', 'EditorL', 105, 180, 'SEARCH', 'Editor@123', 'EditorL_no_format_KO'),
    Array('libro', 'EditorL', 105, 181, 'SEARCH', 'José Martínez', true),
    Array('libro', 'EditorL', 106, 182, 'SEARCH', 'José Martínez', true),

    // PaisEdicionL
    Array('libro', 'PaisEdicionL', 107, 183, 'ADD', '', 'PaisEdicionL_min_size_KO'),
    Array('libro', 'PaisEdicionL', 107, 184, 'ADD', 'España', true),
    Array('libro', 'PaisEdicionL', 108, 185, 'ADD', 'a'.repeat(21), 'PaisEdicionL_max_size_KO'),
    Array('libro', 'PaisEdicionL', 108, 186, 'ADD', 'Francia', true),
    Array('libro', 'PaisEdicionL', 109, 187, 'ADD', 'España123', 'PaisEdicionL_no_format_KO'),
    Array('libro', 'PaisEdicionL', 109, 188, 'ADD', 'Italia', true),
    Array('libro', 'PaisEdicionL', 110, 189, 'ADD', 'Italia', true),
    Array('libro', 'PaisEdicionL', 111, 190, 'EDIT', '', 'PaisEdicionL_min_size_KO'),
    Array('libro', 'PaisEdicionL', 111, 191, 'EDIT', 'España', true),
    Array('libro', 'PaisEdicionL', 112, 192, 'EDIT', 'a'.repeat(21), 'PaisEdicionL_max_size_KO'),
    Array('libro', 'PaisEdicionL', 112, 193, 'EDIT', 'Francia', true),
    Array('libro', 'PaisEdicionL', 113, 194, 'EDIT', 'España123', 'PaisEdicionL_no_format_KO'),
    Array('libro', 'PaisEdicionL', 113, 195, 'EDIT', 'Italia', true),
    Array('libro', 'PaisEdicionL', 114, 196, 'EDIT', 'Italia', true),
    Array('libro', 'PaisEdicionL', 115, 197, 'SEARCH', 'a'.repeat(21), 'PaisEdicionL_max_size_KO'),
    Array('libro', 'PaisEdicionL', 115, 198, 'SEARCH', 'Francia', true),
    Array('libro', 'PaisEdicionL', 116, 199, 'SEARCH', 'España123', 'PaisEdicionL_no_format_KO'),
    Array('libro', 'PaisEdicionL', 116, 200, 'SEARCH', 'Italia', true),
    Array('libro', 'PaisEdicionL', 117, 201, 'SEARCH', 'Italia', true)

);

let pruebas_file_libro = Array(
    // nuevo_archivopdfL
    Array('libro', 'nuevo_archivopdfL', 118, 202, 'ADD', 'max_size_file', Array('documento.pdf', 'application/pdf', 2000001), 'nuevo_archivopdfL_max_size_file_KO'),
    Array('libro', 'nuevo_archivopdfL', 118, 203, 'ADD', 'max_size_file', Array('documento.pdf', 'application/pdf', 1500000), true),
    Array('libro', 'nuevo_archivopdfL', 119, 204, 'ADD', 'type_file', Array('documento.jpg', 'image/jpeg', 1000000), 'nuevo_archivopdfL_type_file_KO'),
    Array('libro', 'nuevo_archivopdfL', 119, 205, 'ADD', 'type_file', Array('documento.pdf', 'application/pdf', 1000000), true),
    Array('libro', 'nuevo_archivopdfL', 120, 206, 'ADD', 'format_name_file', Array('documento@.pdf', 'application/pdf', 1000000), 'nuevo_archivopdfL_format_name_file_KO'),
    Array('libro', 'nuevo_archivopdfL', 120, 207, 'ADD', 'format_name_file', Array('documento.pdf', 'application/pdf', 1000000), true),
    Array('libro', 'nuevo_archivopdfL', 121, 208, 'ADD', 'min_size_name', Array('doc.pdf', 'application/pdf', 1000000), 'nuevo_archivopdfL_min_size_name_KO'),
    Array('libro', 'nuevo_archivopdfL', 121, 209, 'ADD', 'min_size_name', Array('documentopdf.pdf', 'application/pdf', 1000000), true),
    Array('libro', 'nuevo_archivopdfL', 122, 210, 'ADD', 'max_size_name', Array('a'.repeat(105) + '.pdf', 'application/pdf', 1000000), 'nuevo_archivopdfL_max_size_name_KO'),
    Array('libro', 'nuevo_archivopdfL', 122, 211, 'ADD', 'max_size_name', Array('documento.pdf', 'application/pdf', 1000000), true)

);